### ISSUE TITLE
Pagination + i18n

### ISSUE THREAD

**Issue by bastoGrande** [sverrirs/jekyll-paginate-v2#17]
Hey, 

couldn't find something in the old issues, so my question is: Is it somehow possible to set something like this in the config of jekyll?

`permalink    : "/:lang/page/:num/"` - **:lang** is the variable I need to create different versions of the same files.

And I guess to obtain the posts I would need something like this:

`{% for post in paginator.lang.posts %}`
instead of 
`{% for post in paginator.posts %}`

Would be great!!! I hope my problem is understandable.. or maybe you guys have a different approach?

cheers,
bg

**Comment by sverrirs** [comment]
There is support for multiple languages, it is called "locales" https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#filtering-locales

**Comment by sverrirs** [comment]
However there currently is not a macro available to put into the permalink structure.
There hasn't been a great demand for this feature yet but I would be willing to work on this feature if you'd agree to be my test subject ;) 

Could you explain how you would ideally like this feature to work and how you categorize posts in different languages on your site.

**Comment by bastoGrande** [comment]
> I would be willing to work on this feature if you'd agree to be my test subject ;)

JUUUHUUUUU.. 🎉 

Well I try to describe my project-aim as well as possible, because I'm faraway from being a jekyll or website-pro. just want to have a cool blog(-system).. 🙂 

Based on [this](https://www.sylvaindurand.org/making-jekyll-multilingual/) blog-article (especially under goals: "Flexibility" + "Full translation") I was creating my ideas. 

And I thought, when I create dozens of pages and/or posts by the time it would be cool to access them by the same name! So I created the permalink structure like this: `"/%lang%/%page%/"` (for example this static page: /de/about/) for static pages and `"/:lang/posts/:title/"` for posts. 

So in the final folder-root it looks like, this: 
- for each language one folder (containing all pages and posts)
- and the rest of the folders/files like: assets, sitemap.xml, ....

So it would be tidy and cleaned up (with as many languages as could be) and still have the link in between the different versions of the same page/post (`domain/en/about/` and `domain/de/about/`).

Well I guess that's it. If I forgot something, please ask! 😉

**Comment by sverrirs** [comment]
So are you mostly interested in allowing the `locale` value to be replaced in the `permalink` field?

**Comment by bastoGrande** [comment]
Here again what I imagine:

`domain/lang/page/` -> www.github.com/en/issues/

I find it way more tidy and clean than the following:

`domain/locale/page` -> www.github.com/en_WW/issues/

So back to your question: to be honest I don't know how the engine in the background works, but if it's possible to get the lang instead of the locale into the permalink, it would be awesome! :)

**Comment by sverrirs** [comment]
Good point, I am hesitant to duplicate parts of the locale feature. How about if I extract the language part from it and you can use it in the permalink with `:lang`. That way locale supports both these features? 
Sound good?

**Comment by bastoGrande** [comment]
Sounds great! :)

**Comment by bastoGrande** [comment]
One more question, do you have already some kind of list with all possible macros that can be used in the permalink?

That would be great to have for people like me, to see what's possible and what could be a future extension of the plugin (if there are more ideas of future plugin-users.

**Comment by sverrirs** [comment]
For a list of macros currently supported see
https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#formatting-page-titles

**Comment by bastoGrande** [comment]
Sorry, I'm just curious. 

Do you have an idea, when you might work on this issue? Maybe in a week or in one/two/three/whatever months? Cause I can't really continue to setup my blog without this key-feature. Well at least I'm not able to do so.

**Comment by sverrirs** [comment]
Hi again,

Sorry about the delay.

I had another look at your issue and I am a little bit confused as to what you want to achieve. 
If you want to arrange the final output of your site (either posts or pages) into a certain structure under the `_site` folder then that functionality is already built into jekyll by using the `permalink` structure for the page or post itself. You do not need the paginate plugin for this. E.g. for a post:

``` yml
---
layout: post
title:  Geography of Minneapolis for Germans
date:   2016-11-20 19:16:49 +0100
permalink: /de/:title.html
---
```

__However__ if you want to create pagination pages for a specific language for either posts or pages then this falls within the scope of this pagination plugin.

Let's say you have a bunch of German language posts organized in the permalink structure above. 
You just need to modify their front-matter to include a `locale: 'de'` value.

Then to generate a pagination file for the same structure you can simply create a new pagination file somewhere in your site (e.g. your root folder) with the following configuration

``` yml
layout: YOUR_INDEX_PAGE_LAYOUT
permalink: '/de/'
pagination: 
  enabled: true
  locale: 'de'
  permalink: '/:num/'
---
```

_Note: you need to specify the locale explicitly for the rest of the pages as well and update your index.html file to paginate only on that locale. Otherwise your main index.html page will contain all the posts in your site_

**Comment by bastoGrande** [comment]
> Then to generate a pagination file for the same structure you can simply create a new pagination file somewhere in your site (e.g. your root folder) with the following configuration

How do you mean this? I understood I would need to create for example two pagination-files for two languages on my blog? 
And where is the connection? How does your engine know when which pagination file will be needed?

---
And about your example, the first permalink would be the global one (`/de/`)? And the second the pagination specific one (`/:num/`)?
```markdown
---
layout: YOUR_INDEX_PAGE_LAYOUT
permalink: '/de/'
pagination: 
  enabled: true
  locale: 'de'
  permalink: '/:num/'
---
```

sorry, for all the questions.. but I'm still pretty new to the frontend stuff..

**Comment by sverrirs** [comment]
What i meant is that you can create a `index_de.html` under your site root with the following front matter:
``` yml
layout: YOUR_INDEX_PAGE_LAYOUT
permalink: '/de/'
pagination: 
  enabled: true
  locale: 'de'
  permalink: '/:num/'
---
```
What happens is that the pagination permalink will get appended to the main permalink to form an index page at `yoursite.com/de/` which paginates only posts with `locale: 'de'` in their front matter. The paginated pages will then be created under `yoursite.com/de/2`, `yoursite.com/de/3` etc.

You will have to change your default `index.html` to either re-direct to the relevant sub path for language or if you want English pages to be in the root you can have your `index.html` file with the following front matter:

``` yml
layout: YOUR_INDEX_PAGE_LAYOUT
pagination: 
  enabled: true
  locale: 'en'
  permalink: '/:num/'
---
```
This will create pagination pages for posts tagged with `locale: 'en'` under the paths `yoursite.com/` and `yoursite.com/2`, `yoursite.com/3` etc...

If you want explicit language path, e.g. `yoursite.com/en/` and `yoursite.com/en/2` then simply add the permalink in your index.html file like so

``` yml
layout: YOUR_INDEX_PAGE_LAYOUT
permalink: '/en/'
pagination: 
  enabled: true
  locale: 'en'
  permalink: '/:num/'
---
```

Hope this answers and solves your issues :)

**Comment by sverrirs** [comment]
I will consider this issue closed now. Please feel free to re-open if you still have questions :)

**Comment by bastoGrande** [comment]
Hey again,
long time no reply from me.. well, I just gave it up and have now a single-language-blog..  so you can remove the flag, because I won't continue on this.. 😉 

Thank you again for your help!

**Comment by z3nth10n** [comment]
Well, I will need to reopen this. Because actually, I'm using this plugin with your plugin with the ["Jekyll Multiple Languages Plugin"](https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin)... And I'm having some troubles trying to follow what @sverrirs said on [this comment](https://github.com/sverrirs/jekyll-paginate-v2/issues/17#issuecomment-294554649)...

I have the following structure for posts:

![...](https://i.gyazo.com/efdb731a49fb481512e5f14cd8437e72.png)

And I already created two index.html in the root (one for the "en" lang and another for "es")... And then I created another two layouts...

But when I debug the paginator (at myurl.com/en/, for example), the following appears:

`{"per_page"=>5, "posts"=>[], "total_posts"=>0, "total_pages"=>1, "page"=>1, "page_path"=>"/index.html", "previous_page"=>nil, "previous_page_path"=>nil, "next_page"=>nil, "next_page_path"=>nil, "first_page"=>1, "first_page_path"=>"/index.html", "last_page"=>1, "last_page_path"=>"/en/1/index.html", "page_trail"=>nil}`

Is like this plugin isn't compatible with the language one? Because, as you can see, there are some posts at my _i18n folder, but is like the locale isn't able to read them.

What could I do?
