### ISSUE TITLE
filtering a collection

### ISSUE THREAD

**Issue by clarity-strategies** [sverrirs/jekyll-paginate-v2#24]
We have a use case where we want to allow the content creators the ability to set **display: true** in the frontmatter of a collection item. Is it possible to ask the paginator to only fetch members of the collection with display set to true?

**Comment by sverrirs** [comment]
Explicit exclusions have not been implemented into the pagination logic. But you could achieve the same effect by explicit inclusions instead.

What is the exact behavior you want? 

If it is draft status for pages, then jekyll already supports that through [drafts](https://jekyllrb.com/docs/drafts/).

You can have your authors forward date their documents to some ridiculous date (e.g.` date: '3000-01-01T08:00:00'`

If you want them to still be reachable on your site then you can rather than explicitly exclude them, you can explicitly include them into your main page logic by assign them to a `category:published` and then paginate on that category. Or if you already use categories you could use a `tag:published` instead.

**Comment by clarity-strategies** [comment]
Hi

The use case is for two collections(not pages or posts) so I think the
draft folder is not for them
Actually my two collections are 'case-studies' and 'place-studies'.
If I wasn't paginating them I would use a where filter
{% assign published-studies = site.case-studies | where: "published", true
%}

Which would leave behind all the published: false case studies

I wanted to do a where clause with the pagination but I got slapped.

Thanks for explaining

clarity-strategies

**Comment by sverrirs** [comment]
Currently exclusion filters are not available and the `where` filter will not work with the pagination logic.
I don't have any immediate plans on adding this feature but if you have time and would like to add it yourself I would be more than happy to accept a pull request :)

**Comment by sverrirs** [comment]
Closing this issue.

**Comment by albertvolkman** [comment]
Could we possibly re-open this and tag it as an `enhancement`?
