### ISSUE TITLE
Non-slugified tag page titles?

### ISSUE THREAD

**Issue by mmistakes** [sverrirs/jekyll-paginate-v2#6]
Hello. I'm currently experimenting with Autopages to create paginated tag page archives. That's working great but I've run into a small snag.

It appears `site.tags` are being slugified (which is great for permalinks), but when using `page.title` in my layouts and includes it's not as desirable as the tags are no longer initial capped, now have hyphens, etc.

_config.yml

```yaml
autopages:
  tags:
    enabled: true
    layouts:
      - 'autopage_tags.html'
    title: ':tag'
    permalink: '/tag/:tag'
```

Example post YAML

```yaml
tags: [Foo Bar, test, Uppercase]
```

Which outputs `page.title`s like these

```
foo-bar
test
uppercase
```

Is there a `page.` variable available to Autopages that can output the tag name without being slugified, downcased, and without page numbers?

Previously I was using the [jekyll-archives](https://github.com/jekyll/jekyll-archives) plugin to generate my tag pages which now gives me something like this:

```html
<h1>foo-bar</h1>
<p class="excerpt">Posts tagged with foo-bar - page 1 of 62</p>
```

When I'd rather have

```html
<h1>Foo Bar</h1>
<p class="excerpt">Posts tagged with Foo Bar</p>
```

Thanks for your time! This is a great plugin and I hope it finds its way into Jekyll's core.

**Comment by sverrirs** [comment]
Hi Michael, 

Thanks for the kind words and I am glad that you find the plugin useful.

Unfortunately the _key_ which in this case is the tag is normalized and downcased as a part of an internal process while indexing the site pages. This is necessary so that I can let users make minor input errors in their pages (e.g. extra white spaces around the tags, mixed case etc). 

Due to how deeply in the core code this is being done I would have to restructure a few things to get you a human readable unmodified value back.  I will look into this for you as I think this would be a valuable feature to have, but it may take a little while to complete :)

**Comment by mmistakes** [comment]
Sounds good. Thanks for considering it.

**Comment by sverrirs** [comment]
@mmistakes Michael, try it now. The way to obtain the original value is documented here https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-AUTOPAGES.md#obtaining-the-original-tag-or-category-name

**Comment by mmistakes** [comment]
Works like a charm.

Is there a way to output the display name along with the page x of x string? I tried swapping `page.title` with `page.autopages.display_name` but it loses the `Page :num of :max` bit.

```html
page.tag = "Foo Bar"

<title>{{ page.title }}<title> ~> <title>foo-bar - Page x of x</title>
<title>{{ page.autopages.display_name }}</title> ~> <title>Foo Bar</title>
```

**Comment by sverrirs** [comment]
Sure thing. Could you do me a favor and open a new ticket for this feature. That way I won't forget (since this one has already been fixed and closed)
