### ISSUE TITLE
generate page "view-all"

### ISSUE THREAD

**Issue by DjonyBastone** [sverrirs/jekyll-paginate-v2#60]
Hello!!!   
Pagination works as expected.
For SEO you need to generate a pages with all the blog posts or category:
```
blog/ (20 posts)
|
|_blog/page2/ (20 posts)
|
|_blog/page3/ (20 posts)
|
|_blog/page3/ (20 posts)
|
|_blog/view-all/ (all posts)
|
|____yahoooooooo/ (20 posts, category: yahoooooooo)
|
|____yahoooooooo/page2/ (20 posts)
|
|____yahoooooooo/page3/ (20 posts)
|
|____yahoooooooo/view-all/ (all posts)
|
|____tro-lo-lo/ (20 posts, category: tro-lo-lo)
|
|____tro-lo-lo/page2/ (20 posts)
|
|____tro-lo-lo/page3/ (20 posts)
|
|____tro-lo-lo/view-all/ (all posts)
```

How to generate page "view-all" ? Please help me

P.S. [google recommendations for pagination](https://webmasters.googleblog.com/2013/04/5-common-mistakes-with-relcanonical.html)

**Comment by ibrado** [comment]
Hi @DjonyBastone 

Since `view-all` won't be paginated, this is more of a general Jekyll question, but I'll answer here anyway... 😄 I hope @sverrirs doesn't mind.

In your source folder `blog`, make a `view-all.md` like so:

```html
---
layout: page
---
These are all the posts:

{% for post in site.posts %}
  <div><a href="{{post.url}}">{{post.title}}</a><br/>
  {{ post.content }}
  </div>
{% endfor %}
```

You can make a `blog/yahoooooooo` folder that also contains a `view-all.md`:

```html
---
layout: page
---
These are the posts in the `yahoooooooo` category:

{% assign cat_posts = site.posts | where_exp: "item", "item.categories contains 'yahoooooooo'" %}
{% for post in cat_posts %}
  <div><a href="{{post.url}}">{{post.title}}</a><br/>
  {{ post.content }}
   </div>
{% endfor %}
```

The above assumes you have pretty permalinks. If not, you could make `blog/view-all/index.md` and `blog/category/view-all/index.md` instead of `blog/view-all.md` and `blog/category/view-all.md`.

**Comment by DjonyBastone** [comment]
Many thanks - works
